### ISSUE TITLE
와 으니 쩐다!

### ISSUE THREAD

**Issue by sigridjineth** [euneestella/fifa-online-ranker-analysis#1]
으니 으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니으니

**Comment by realsigridjin** [comment]
@euneestella 너 혹시 피파하냐?

**Comment by eunhee-dev** [comment]
ㅋㅋㅋㅋㅋㅋ 피파는 예~전에 어깨너머로 구경한 게 다.............

**Comment by realsigridjin** [comment]
@euneestella 오 칼답 오진다. 깃헙 알림 불편한데 대박이야. ㅎㅎ

**Comment by eunhee-dev** [comment]
메일 칼같이 오던데? ㅋㅋㅋㅋㅋ

**Comment by realsigridjin** [comment]
@euneestella 아 메일............ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 너 롤은 안하냐?

**Comment by eunhee-dev** [comment]
난 RPG 외길인생이다

**Comment by realsigridjin** [comment]
@euneestella 3일 전에 메이플 해봤는데 스토리 너무 길더라 노잼됨

**Comment by eunhee-dev** [comment]
진정한 오타쿠는 스토리를 보기 위해 게임하는 것이거늘... 아직 멀었군

**Comment by realsigridjin** [comment]
@euneestella 롤 캐릭터 분석해보는건 어때?

**Comment by eunhee-dev** [comment]
그 많은 챔피언 언제 공부해본담... 이라고 생각해보니까 메이플도 직업 40개 넘네

**Comment by realsigridjin** [comment]
@euneestella 너의 미래는 블루홀? 크래프톤?

**Comment by eunhee-dev** [comment]
어디든 뽑아주시면 즐거운 게임 덕후

**Comment by realsigridjin** [comment]
@euneestella 넥슨 인턴해라
